/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package culturarte.paneles;


/*
 Pasos para cambiar el tamaño de este panel:
 1) Abrir este archivo: UCSeguirUsuarioPanel.java
2) En el constructor (UCSeguirUsuarioPanel), modificar la dimensión en setPreferredSize:
   this.setPreferredSize(new java.awt.Dimension(W, H));
   donde W es el ancho y H la altura en píxeles.
3) Recompilar el proyecto (mvn/gradle/NetBeans) y ejecutar para probar.
*/

import javax.swing.JOptionPane;
import culturarte.casosuso.UsuarioService;
import culturarte.casosuso.FollowService;
import culturarte.casosuso.Usuario;

/**
 *
 * @author tecnologo
 */
public class UCSeguirUsuarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form UCSeguirUsuarioPanel
     */
public UCSeguirUsuarioPanel() {
    initComponents();
        // --- Tamaño predeterminado: 1000 x 1000 ---
        // Para cambiarlo: editar esta línea o seguir los pasos en el README dentro del proyecto.
        this.setPreferredSize(new java.awt.Dimension(500, 100));

                // <assistant-fixed-sizes> Ajustes de tamaño para mantener la misma lógica visual (labels a la izquierda, botones abajo, tamaños fijos)
        try {
            // intentar ajustar jPanel1 mediante reflection (si existe)
            try {
                java.lang.reflect.Field fPanel = this.getClass().getDeclaredField("jPanel1");
                fPanel.setAccessible(true);
                Object p = fPanel.get(this);
                if (p instanceof javax.swing.JPanel) {
                    javax.swing.JPanel panel = (javax.swing.JPanel)p;
                    try { panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10)); } catch (Exception ex) {}
                    try { panel.setPreferredSize(new java.awt.Dimension(760,480)); } catch (Exception ex) {}
                }
            } catch (Exception ex) { /* no jPanel1 en este panel */ }

            // etiquetas: tamaño consistente vía reflection
            for (int i=1;i<=20;i++) {
                try {
                    java.lang.reflect.Field f = this.getClass().getDeclaredField("jLabel"+i);
                    f.setAccessible(true);
                    Object obj = f.get(this);
                    if (obj instanceof javax.swing.JLabel) {
                        try { ((javax.swing.JLabel)obj).setPreferredSize(new java.awt.Dimension(120,20)); } catch (Exception e) {}
                    }
                } catch (Exception e) {}
            }

            // campos de texto / areas comunes: aumentar columnas/preferred size si existen
            String[] textFields = new String[] { "txtNombre","txtApellido","txtEmail","txtFecha","txtNickname","txtDireccion","txtWeb","txtLugar","txtCosto","txtDuracion","txtGenero","txtTelefono","txtBiografia" };
            for (String nm: textFields) {
                try {
                    java.lang.reflect.Field f = this.getClass().getDeclaredField(nm);
                    f.setAccessible(true);
                    Object obj = f.get(this);
                    if (obj instanceof javax.swing.JTextField) {
                        try { ((javax.swing.JTextField)obj).setColumns(20); ((javax.swing.JTextField)obj).setPreferredSize(new java.awt.Dimension(200,24)); } catch (Exception ex) {}
                    } else if (obj instanceof javax.swing.JTextArea) {
                        try { ((javax.swing.JTextArea)obj).setColumns(20); ((javax.swing.JTextArea)obj).setPreferredSize(new java.awt.Dimension(400,100)); } catch (Exception ex) {}
                    } else if (obj instanceof javax.swing.JComboBox) {
                        try { ((javax.swing.JComboBox)obj).setPreferredSize(new java.awt.Dimension(200,24)); } catch (Exception ex) {}
                    }
                } catch (Exception e) {}
            }

            // botones: forzar tamaño y ubicacion en jPanel2 si existe
            try {
                java.lang.reflect.Field f2 = this.getClass().getDeclaredField("jPanel2");
                f2.setAccessible(true);
                Object p2 = f2.get(this);
                if (p2 instanceof javax.swing.JPanel) {
                    try { ((javax.swing.JPanel)p2).setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10)); } catch (Exception ex) {}
                }
            } catch (Exception e) {}
        } catch (Exception e) {
            // no hacer nada si falla
        }
        // </assistant-fixed-sizes>

    cargarUsuarios(); // Llama al método para llenar los combos
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboSeguidor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboSeguido = new javax.swing.JComboBox<>();
        btnSeguir = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Seguidor:");
        add(jLabel1);

        comboSeguidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSeguidor.setPreferredSize(new java.awt.Dimension(270, 24));
        comboSeguidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguidorActionPerformed(evt);
            }
        });
        add(comboSeguidor);

        jLabel2.setText("Seguido:");
        add(jLabel2);

        comboSeguido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSeguido.setPreferredSize(new java.awt.Dimension(270, 24));
        comboSeguido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguidoActionPerformed(evt);
            }
        });
        add(comboSeguido);

        btnSeguir.setText("Seguir");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });
        add(btnSeguir);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
    try {
        if (comboSeguidor.getSelectedItem() == null || comboSeguido.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione seguidor y seguido");
            return;
        }

        String seguidorId = ((String)comboSeguidor.getSelectedItem()).split(":")[0].trim();
        String seguidoId = ((String)comboSeguido.getSelectedItem()).split(":")[0].trim();

        try {
            javax.persistence.EntityManager em = culturarte.casosuso.JPAUtil.getEntityManager();
            try {
                em.getTransaction().begin();
                culturarte.casosuso.Usuario seg = em.find(culturarte.casosuso.Usuario.class, seguidorId);
                culturarte.casosuso.Usuario segd = em.find(culturarte.casosuso.Usuario.class, seguidoId);
                if (seg != null && segd != null) {
                    javax.persistence.TypedQuery<culturarte.casosuso.Follow> q = em.createQuery("SELECT f FROM Follow f WHERE f.seguidor.id = :s AND f.seguido.id = :t", culturarte.casosuso.Follow.class);
                    q.setParameter("s", seguidorId);
                    q.setParameter("t", seguidoId);
                    java.util.List<culturarte.casosuso.Follow> exists = q.getResultList();
                    if (exists.isEmpty()) {
                        culturarte.casosuso.Follow f = new culturarte.casosuso.Follow();
                        f.setSeguidor(seg);
                        f.setSeguido(segd);
                        em.persist(f);
                        em.getTransaction().commit();
                        JOptionPane.showMessageDialog(this, "Ahora sigue");
                    } else {
                        em.getTransaction().rollback();
                        JOptionPane.showMessageDialog(this, "Ya sigue");
                    }
                } else {
                    em.getTransaction().rollback();
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado");
                }
            } finally {
                if (em != null && em.isOpen()) em.close();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }    
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
}//GEN-LAST:event_btnSeguirActionPerformed

    private void comboSeguidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeguidoActionPerformed

    private void comboSeguidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeguidorActionPerformed

    private void cargarUsuarios() {
    try {
            comboSeguidor.removeAllItems();
            comboSeguido.removeAllItems();
            java.util.List<String> _list = culturarte.casosuso.LegacyDB.listUsuariosByTipo(null);
            // using legacy db helper to list all users
            javax.persistence.EntityManager em = culturarte.casosuso.JPAUtil.getEntityManager();
            try {
                javax.persistence.TypedQuery<culturarte.casosuso.Usuario> q = em.createQuery("SELECT u FROM Usuario u", culturarte.casosuso.Usuario.class);
                java.util.List<culturarte.casosuso.Usuario> users = q.getResultList();
                for (String item : _list) {
                        comboSeguidor.addItem(item);
                        comboSeguido.addItem(item);
                    }
            } finally {
                if (em != null && em.isOpen()) em.close();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeguir;
    private javax.swing.JComboBox<String> comboSeguido;
    private javax.swing.JComboBox<String> comboSeguidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
