version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: culturarte
      MYSQL_USER: tecnologo
      MYSQL_PASSWORD: tecnologo
    ports:
      - "33320:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
